### ISSUE TITLE
ComBat in large sample size

### ISSUE THREAD

**Issue by dbergeba** [Jfortin1/ComBatHarmonization#1]
Hello, I am trying to run ComBat in Matlab using a relatively large sample size (n= 300) which contains DTI data from two different sites. Although I have been able to run ComBat, it returns a matrix with only NA in it. Any suggestions to clear this issue? 
Thanks

**Comment by Jfortin1** [comment]
Is that possible that there were NA values in the original matrix?

**Comment by dbergeba** [comment]
Hi, thanks, I removed the NAs and it works. Would you expect significant differences between running combat in R or matlab? This is because before running ComBat there are significant differences in patients vs. controls, that do no exist any more after ComBat. I was wondering whether the R scripts are more accurate than the matlab ones.

**Comment by Jfortin1** [comment]
Did you include the patient/control variable in the Combat function as a biological variable?

**Comment by dbergeba** [comment]
Yes,
   Also age and gender. I also tried only with the patient/control variable.

**Comment by Jfortin1** [comment]
I just tested the Matlab and R scripts on a test dataset; they both lead to the same normalized values. If your two sites are not confounded with patient/control status, this is an unlikely result. Would you mind sharing your code either by email (fortin946 at gmail.com) or here so that I can help you?

**Comment by dbergeba** [comment]
Thanks,
  Here I attach my script.
Thanks a lot for your help

[Step21_comBat_FW_wv4.m.txt](https://github.com/Jfortin1/ComBatHarmonization/files/2116813/Step21_comBat_FW_wv4.m.txt)

**Comment by Jfortin1** [comment]
2 questions:
(1) What is the evidence that the patient/control differences are lost after harmonization?
(2) What is the confounding level between your variables?

**Comment by dbergeba** [comment]
Hello
    Attached you will find a boxplot with the plotted values before and 
after running Combat, showing also the t-test.
    I do not understand what you mean with "the confounding level 
between your variables". If by this you mean the variables whose 
variability I want to preserve after ComBat, these are age, gender, 
baseline/follow-up and group(patients vs. controls). I tried only 
keeping group, and it made no difference.
  I am running ComBat with Free-Water scalar values which have a 
substantial different distribution of FA values for example. Would it be 
better to run ComBat in R that allows to use the option "without 
empyrical Bayes computation"?

Thanks

**Comment by dbergeba** [comment]
Thanks for your interest, I would like to kindly ask one more quick 
question:
   Is it better to feed ComBat with masked or unmasked images? I mean, 
should I expect a more accurate result with skull-striped imaged or even 
with white matter or gray matter masked images?

Thanks again.
