### ISSUE TITLE
harmonize DTI files

### ISSUE THREAD

**Issue by chen2mg** [Jfortin1/ComBatHarmonization#10]
Hi,

I am using combat to harmonize DTI nifti file, and I am getting the error: 
"Error. There are rows with constant values across samples. Remove
these rows and rerun ComBat."

I know there are many 0s in my 3D nifti image data, I am wondering if I how can I using combat in for those data?

Thanks.

**Comment by Jfortin1** [comment]
Hi,

You can:
- Remove the rows that have constant values across all images
- Run ComBat
- Add back the rows with constant values. 

JP

**Comment by chen2mg** [comment]
Awesome! Thanks.
