### ISSUE TITLE
Non-parametric form by Matlab

### ISSUE THREAD

**Issue by Yingping-LI** [Jfortin1/ComBatHarmonization#12]
Thanks for sharing the code!

I am using your Matlab code, and parametric format works perfectly, but non-paramteric format can't work, most values  are"NaN" after ComBat.

Can you help me with this problem? Thank  you very much.

**Comment by Jfortin1** [comment]
@Yingping-LI 
I cannot help without your data and/or your code. Please provide there, thanks.

**Comment by Yingping-LI** [comment]
@Jfortin1 

Thank you very much for your kind reply, and I figured out the reason now.
Have a nice day: )
