### ISSUE TITLE
Non-parametric implementation in Python

### ISSUE THREAD

**Issue by Jfortin1** [Jfortin1/ComBatHarmonization#15]
@Shotgunosine Migrating neuroCombat here since this does not seem to be supported my previous co-author.

**Comment by Shotgunosine** [comment]
Thanks! I'd love to see that happen. I started looking into it, but got scared off by the somewhat opaque optimization code in the R version.

**Comment by Shotgunosine** [comment]
Also, I don't know if you know about[ neurostars.org.](neurostars.org). It's a help board for neuroimaging analysis. Questions related to combat have come up there a few times and I'm sure folks would love to hear your opinion:

https://neurostars.org/search?q=combat

**Comment by Jfortin1** [comment]
@Shotgunosine 
Both arguments "eb" and "parametric" added to the Python code: https://github.com/Jfortin1/ComBatHarmonization/commit/5f9a29698c23711434c747708ead0fd942e9a294

Thanks for mentioning the neurostarts.org, I was actually not aware of its existence. I'm glad to see there is an interest to use ComBat, and I do have a lot to say re. cross-validation -- I've thought about it at length. I'm going to summarize my thoughts and write a few posts in the next couple of days.
