### ISSUE TITLE
[Python] Dividing by zeros in standardize_accros_features function

### ISSUE THREAD

**Issue by Jfortin1** [Jfortin1/ComBatHarmonization#16]
(neuroCombat migrated here for maintainability) 

From @RocaVincent:

Hi,

Thanks for this code,

Line 170 of neuroCombat.py file, I got a problem when it divides using the following term : np.dot(np.sqrt(var_pooled), np.ones((1, n_sample))). In this term, almost half of the coefficients are zeros so I got a RuntimeWarning and Nan values create problems later. Have you any idea why I got zeros and how I can fix this problem ?

Thanks

**Comment by Figsandcitrus** [comment]
Hi @Jfortin1 Wanted to see if this is the same problem in Python, and if you have any suggestion. I have a large matrix with lots of zeros (see scatter plot for two random features). I get the following error and a NaN matrix that obviously doesn't plot. I have used it for other data without this many zeros without problem.

```
[neuroCombat] Creating design matrix
[neuroCombat] Standardizing data across features
/usr/local/lib/python3.7/dist-packages/neuroCombat/neuroCombat.py:233: RuntimeWarning: invalid value encountered in true_divide
  s_data = ((X- stand_mean) / np.dot(np.sqrt(var_pooled), np.ones((1, n_sample))))
[neuroCombat] Fitting L/S model and finding priors
[neuroCombat] Finding parametric adjustments
[neuroCombat] Final adjustment of data
```

![image](https://user-images.githubusercontent.com/60196063/109563661-1038fb00-7aae-11eb-8548-ad00e64c3af4.png)

**Comment by Jfortin1** [comment]
@Figsandcitrus Yes this problem has occurred for both Matlab and R implementations (which I just fixed a few minutes ago). I'll fix this for Python today

**Comment by Jfortin1** [comment]
Should be fixed in https://github.com/Jfortin1/ComBatHarmonization/commit/3b6f16a060618c022983005d3a521909993a9e49
