### ISSUE TITLE
Error in apply(data, 1, sd) : dim(X) must have a positive length

### ISSUE THREAD

**Issue by jlhanson5** [Jfortin1/ComBatHarmonization#2]
Hello ComBatHarmonization users, 

I was trying to test-drive ComBat Harmonization, but ran into some issues with the apply function. I'm unsure if there's an issue with another R library or my R version (?). 

I'm using a mac (10.13.5) with R-studio 1.1.453 and R 3.5.0

> source("scripts/utils.R"); source("scripts/combat.R") 
> p=10000
> n=10
> batch = c(1,1,1,1,1,2,2,2,2,2) #Batch variable for the scanner id
> dat = matrix(runif(p*n), p, n) #Random Data matrix
> nrow(dat)
[1] 10000
> ncol(dat)
[1] 10
> 
> data.harmonized <- combat(dat=dat, batch=batch)
 Show Traceback
 Rerun with Debug
 Error in apply(data, 1, sd) : dim(X) must have a positive length `

I wondered if others had run into this issues? 
Any suggestions for troubleshooting this?

Thanks much!
Jamie.

**Comment by Jfortin1** [comment]
Hi Jamie,

Sorry about that -- I just fixed it and updated the scripts in this repo. Thanks for finding the issue.

JP

**Comment by jlhanson5** [comment]
Perfect, thank much!
