### ISSUE TITLE
aprior formular

### ISSUE THREAD

**Issue by zh1peng** [Jfortin1/ComBatHarmonization#21]
Hello,
I have a question regarding the aprior function,
From the equation that is shown in Johnson 2007
![image](https://user-images.githubusercontent.com/25647407/83903486-381c4d80-a72c-11ea-95b7-c4c372fa81b2.png)

y=(2*s2+m^2)/s2 in the aprior function confused me, 
if I understand it correctly, should it be written as 
 y=(2*s2+m)/s2?

zhipeng

**Comment by Jfortin1** [comment]
There's actually a typo in the original Johnson 2007 paper equation; if you solve the equations in their supplementary material, you'll find that lambda = (V^2+2S^2)/S^2. 
Both the ComBat original code implementation and our code implementation use the correct formula, so all good!
