### ISSUE TITLE
batch needed to be ordered

### ISSUE THREAD

**Issue by sreevalsansmenon** [Jfortin1/ComBatHarmonization#22]
I had an issue in MATLAB when the batch was unordered. I didn't have data from sites 1 and 2 but had the other 19 sites (from 21 sites in ABCD). But n_batch showed 21 and had some error. I tried using "batchmode(:,~any(batchmod,1))=[];" inline 15 to remove zero columns.

**Comment by Jfortin1** [comment]
Thanks for reporting the bug. Will work on it now.

**Comment by Jfortin1** [comment]
Should be fixed in https://github.com/Jfortin1/ComBatHarmonization/commit/0e10ddef8364c07c792bb07ac6e57f47dcdaffd7
