### ISSUE TITLE
Call neuroCombat without ref_batch

### ISSUE THREAD

**Issue by RocaVincent** [Jfortin1/ComBatHarmonization#24]
Hi,

I want to use the Python version of neuroCombat and I see that in the _neuroCombat_ function there is an optional argument _ref_batch_. I understand the role of the ref batch thanks to [one of the ComBat papers](https://www.sciencedirect.com/science/article/pii/S105381191730931X?via%3Dihub), but I don't understand how it can be optional since all theoretical explanations use a reference site. Can you tell me where I can find explanations about ComBat used without a reference site ?

Thanks in advance

**Comment by Jfortin1** [comment]
Hi @RocaVincent, 

When no `ref_batch` is specified, the intercept in the model is taken as the average measurements across all sites and sites, and site/scanner effects are expressed as deviations relative to that average. When a `ref_batch` site is provided, site/scanner effects are expressed as deviations relative to that reference site.

**Comment by anlijuncn** [comment]
Thanks for the issue, it is really important to me

**Comment by RocaVincent** [comment]
Thanks @Jfortin1 for your quick response !
