### ISSUE TITLE
mod.mean in neuroCombatFromTraining()

### ISSUE THREAD

**Issue by anlijuncn** [Jfortin1/ComBatHarmonization#25]
Hi Fortin, 

Thanks for your update, I found the R version of ComBat begins to support using estimation from training data on unseen data. 

For the function neuroCombatFromTraining(), I am curious about why you use [`rowMeans(mod.mean)` ](https://github.com/Jfortin1/ComBatHarmonization/blob/71ceee1540ca8daed62db1d9e1ac32344edc0f09/R/neuroCombat/R/neuroCombat.R#L148) instead of using something like `beta.hat * X_{new_data}`. `beta_hat` is estimated from training data, `X_{new_data}` is the covariates from new dataset. 

It seems quite straightforward to me, is there is any reason why you do not do this? 

Thanks!

**Comment by Jfortin1** [comment]
This option (providing biological covariates in the test dataset) isn't supported for now, but under development. While straightforward in theory, this can be problematic in practice if the covariates differ in the test dataset.
