### ISSUE TITLE
Possible to use parallelization to speed up non-parametric estimation in R?

### ISSUE THREAD

**Issue by dpagliaccio** [Jfortin1/ComBatHarmonization#27]
Hi
I am testing out neuroCombat to harmonize fMRI data across two sites. The parametric version works great even on a larger number of input features. But it takes an exceedingly long time to run the non-parametric version with thousands of features.
I was wondering if it would be possible to use parallel processing to speed this up? Particularly the getEbEstimators helper function for "Finding non-parametric adjustments"
Thanks!

**Comment by Jfortin1** [comment]
Thank you for the suggestion. `BiocParallel` options now added to v 1.0.7.(https://github.com/Jfortin1/ComBatHarmonization/commit/145bce4075c84e3d99358061928f4fafb4db70ac)
