### ISSUE TITLE
How can I detect overcorrection?

### ISSUE THREAD

**Issue by Lux91** [Jfortin1/ComBatHarmonization#33]
Hi guys, I'm using neuroCombat (python version) to assess the impact of different CT machines (and other stuff) on a radiomic dataset.
The only thing that I'm still trying to figure out is how to determine if neuroCombat leads me to overcorrection. 
Can someone help?
Sorry, but I usually analyze other types of data and this is my first time working on features from CT images.

Thanks in advance :)

**Comment by Jfortin1** [comment]
That's a valid question/problem, but this is probably not the place to ask this given that this is not an issue relevant to the software itself. Closing it.
