### ISSUE TITLE
Error using combat in Matlab, error about vertcat although dimensions of input are right

### ISSUE THREAD

**Issue by narzouni** [Jfortin1/ComBatHarmonization#35]
Hello Experts,

When I run combat using Matlab, I get the following error about dimensions of the the arrays although my batch is a vector of 125, and my data is 9 features by 125 (9x125).

I am using mode = []; 
DataHarmonized = combat(DataVol, batch, mod, 0);

Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in combat (line 80)
		delta_hat = [delta_hat; var(s_data(:,indices)')];

**Comment by andersonwinkler** [comment]
I keep having the same problem...

```
Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Error in combat (line 80)
		delta_hat = [delta_hat; var(s_data(:,indices)')];
```

**Comment by andersonwinkler** [comment]
ok, not surprisingly, if a batch has just 1 subject, then this error emerges.

The solution is to remove such tiny batches.
