### ISSUE TITLE
Working with voxel-wise data

### ISSUE THREAD

**Issue by Melissa1909** [Jfortin1/ComBatHarmonization#36]
Hey combat users,
I have a question regarding the use of voxel-wise data for combat (Python). I have implemented neurocombat for ROI-wise data, but I don't know how to input voxel-wise data which would require the shape of features (= participants) x samples (= 3D voxels). Can someone help on how to include 3D voxel information per participant into a numpy array?
Best, Melissa

**Comment by Jfortin1** [comment]
See https://github.com/Jfortin1/neuroCombat/issues/14
