### ISSUE TITLE
 Error in solve.default(t(design) %*% design)?

### ISSUE THREAD

**Issue by jlhanson5** [Jfortin1/ComBatHarmonization#6]
Hello,

I previously got ComBat to work with some test data, but recently ran into an error when working with "real data". [The data I'm working with is located here](https://www.dropbox.com/sh/wuly3e4but7wu6h/AAAyot4oeqPpTmLCpCjoqpsca?dl=0). 

My basic R syntax was--

```
source("scripts/utils.R");
source("scripts/combat.R")

dat<-t(as.matrix(read.csv("Freesurfer_HBN_w_Site_For_Combat.csv")))
batch<-read.csv("HBN_site.csv")
batch<-t(batch$Site)
data.harmonized <- combat(dat=dat, batch=batch)
```

After I run that command, I get the following error--

<img width="842" alt="untitled" src="https://user-images.githubusercontent.com/7240261/46707924-23f81400-cc0a-11e8-833b-c7c6eb8eb77c.png">

Any thoughts re: what I might be doing incorrectly? 
Thanks much!

All the best,
Jamie.

**Comment by Jfortin1** [comment]
Hi Jamie,

I cannot reproduce your analysis since the file "HBN_site.csv" is not part of your data directory.

**Comment by jlhanson5** [comment]
Ah I apologizes, I uploaded the incorrect file to dropbox. The correct files should be there now ([link again](https://www.dropbox.com/sh/wuly3e4but7wu6h/AAAyot4oeqPpTmLCpCjoqpsca?dl=0)).

**Comment by Jfortin1** [comment]
I used the following code:

```{R}
dat <- t(as.matrix(read.csv("Freesurfer_HBN_w_Site_For_Combat.csv")))
batch <- read.csv("HBN_site.csv")$Site 
data.harmonized <- combat(dat=dat, batch=batch)
```
and the code ran smoothly. 

JP

**Comment by jlhanson5** [comment]
Ah yes, that seems to have done it. I must have misspecified Site/Batch. Thanks for the help with this!
