### ISSUE TITLE
Is it possible to use ComBat in native space?

### ISSUE THREAD

**Issue by tongluobing** [Jfortin1/ComBatHarmonization#7]
Hello,
We know that ComBat requires the images to be registered to a common template space. For some of our analyses, we want to get the value of subjects in native space. Is it possible to use ComBat in native space? Or can we firstly use ComBat for all in a template space, then project the subjects back to native space? Any risk for this procedure (i.e. introduce the bias back again)?

Thanks!

**Comment by Jfortin1** [comment]
ComBat requires the voxels to be aligned across subjects, therefore the need of a registration to template. As you suggested, back transforming ComBat-normalized values to subject space is a viable solution. We have not investigated the performance of ComBat across different registration algorithms, but we do not think this introduces a bias of any sort.

**Comment by tongluobing** [comment]
Thanks. It really helps.
